apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesiesta.engine.fullname" . }}
  labels:
    {{- include "kubesiesta.labels" . | nindent 4 }}
    app.kubernetes.io/component: engine
spec:
  type: {{ .Values.engine.service.type }}
  selector:
    {{- include "kubesiesta.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: engine
  ports:
    - name: http
      port: {{ .Values.engine.service.port }}
      targetPort: http
